config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :trips
  get '/trips/days/:id', to: 'trips#day', as: :day_trip
  get '/your_trip', to: 'trips#your_trip', as: :your_trip
  get '/your_trip/next', to: 'trips#next', as: :next_day
  get '/your_trip/prev', to: 'trips#prev', as: :prev_day
  get '/about', to: 'pages#about', as: :about
  resources :categories
  resources :activities do
    member do
      patch :assign_day
      patch :remove_day
    end
  end

  get '/components', to: 'pages#components', as: :components

end

app/models/trip.rb
class Trip < ApplicationRecord
  attr_accessor :seed

  belongs_to :user, optional: true
  has_many :activities, dependent: :nullify

  validates :city, :start_date, presence: true
  # validates :duration, presence: true
  validate :end_after_start?, on: :create
  validate :date_future?, on: :create

  private

  has_many :activities
  has_many :days, dependent: :destroy

  def date_future?
    return if seed

    errors.add(:start_date, "can't be in the past") if start_date < Date.today

    errors.add(:end_date, "can't be in the past") if end_date < Date.today
  end

  def end_after_start?
    return if seed

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show destroy edit update]
  def index
    @trips = Trip.where(user: current_user)
  end

  def show
    @days = @trip.days.order(:date).distinct
    # set_activities
    @next_day = @trip.days.order(:date).first


    activities = @trip.days.map { |day| day.activities }.flatten

    ids = activities.map { |act| act.day_id }.uniq

    urls = ['https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747766/love_3_tfswx3.png']

    marker_images = {}

    ids.each_with_index do |id, index|
      marker_images[id] = urls[index]
    end



    @markers = activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: marker_images[activity.day_id]

      }
    end
  end

  def edit
    @day = @trip.days.order(:date).distinct
  end

  def update
    # connect the activity)id with the days[:date]

    @days = @trip.days
    @days.each do |day|
      activity_ids = params[day.id.to_s][:activities] # array
      activity_ids.each do |id|
        activity = Activity.find(id)
        activity.update(day_id: day.id)
      end
      # @trip.update(trip_params)
    end
    redirect_to trip_path(@trip)
  end

  def day
    @day = Day.find(params[:id])
    @trip = @day.trip
    # set_activities
    @next_day = @trip.days.where('id > ?', @day.id).first
    @prev_day = @trip.days.where('id < ?', @day.id).last

    activities = @day.activities

    ids = activities.map { |act| act.day_id }.uniq

    urls = ['https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747766/love_3_tfswx3.png']

    marker_images = {}

    ids.each_with_index do |id, index|
      marker_images[id] = urls[index]
    end

    @markers = activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: marker_images[activity.day_id]
      }
    end
    @days = [@day]
    render 'show'
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  def create
    @start_date = session[:start_date]
    @end_date = session[:end_date]
    @city = session[:city]
    @trip = Trip.new(city: @city, start_date: @start_date, end_date: @end_date)
    @activity_ids = params[:search].keys # [2,4,6,8]
    @trip.user = current_user if user_signed_in?
    @trip.save
    session[:current_trip] = @trip.id
    Activity.where(id: @activity_ids).update_all(trip_id: @trip.id)
  end

  def your_trip
    if session[:current_trip]
      @trip = Trip.find(session[:current_trip])
    else
      create
    end






    if @trip.activities.any? { |act| act.day }
      # raise
      @city = @trip.city


       # {}

      @result = @trip.days.map do |day|
        {activities: Activity.where(day: day), day: day}
      end

      # @result = [{activities: @trip.activities.where.not(day_id: nil)}]
      # puts 9
      @next = 1
    else
      @trip.days.destroy_all
      if params[:search].present?
        @trip.activities.update_all(trip_id: nil)
        params[:search].each_key do |id|
          Activity.find(id).update_columns(trip_id: @trip.id)
        end
      end
      @next = 0
      @prev = nil
      calculate_day_plan
    end

    Activity.where(id: session[:activity_ids]).update_all(trip_id: @trip.id)

    acts = []
    @result.each do |t|
      acts << t[:activities] # [[act1, act2], [act4]]
    end


    ids = acts.flatten.map { |act| act.day_id }.uniq

    urls = ['https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747766/love_3_tfswx3.png']

    marker_images = {}

    ids.each_with_index do |id, index|
      marker_images[id] = urls[index]
    end


    @markers = acts.flatten.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: marker_images[activity.day_id]
      }
    end
    # binding.pry
  end

  def next
    @trip = Trip.find(session[:current_trip])
    # calculate_day_plan
    day =  @trip.days[params[:day].to_i - 1]
    @day = { day: @trip.days[params[:day].to_i - 1], activities: Activity.where(day: day) }



    # @next = @result[params[:day].to_i] ? params[:day].to_i + 1 : nil
    # @prev = @next ? @next - 1 : params[:day].to_i - 1

    @next = params[:day].to_i + 1 unless params[:day].to_i == @trip.days.length
    @prev = params[:day].to_i - 1 unless params[:day].to_i == 1

    @result = [@day]


     activities = @trip.activities.where.not(day_id: nil)

    ids = activities.map { |act| act.day_id }.uniq

    urls = ['https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747766/love_3_tfswx3.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png' ]

    marker_images = {}

    ids.each_with_index do |id, index|
      marker_images[id] = urls[index]
    end
    # current_user = User.find_by_id(session[:current_user_id])
    # activities that the user choosed

    # raise

    @markers = @day[:day].activities.map do |activity|
      {
        next: true,
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: marker_images[activity.day_id]

      }
    end

    # binding.pry
        @city = @trip.city

    if @result[0] && @result[0][:day]
      @date = @result[0][:day][:date]
    else
      @date
    end
    if params[:show].present?
      set_activities
      render 'show'
    else
      render 'your_trip'
    end
  end

  def prev
@trip = Trip.find(session[:current_trip])
    # calculate_day_plan
    day =  @trip.days[params[:day].to_i - 1]
    @day = { day: @trip.days[params[:day].to_i - 1], activities: Activity.where(day: day) }



    # @next = @result[params[:day].to_i] ? params[:day].to_i + 1 : nil
    # @prev = @next ? @next - 1 : params[:day].to_i - 1

    @next = params[:day].to_i + 1 unless params[:day].to_i == @trip.days.length
    @prev = params[:day].to_i - 1 unless params[:day].to_i == 1

    @result = [@day]


     activities = @trip.activities.where.not(day_id: nil)

    ids = activities.map { |act| act.day_id }.uniq

    urls = ['https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747766/love_3_tfswx3.png']

    marker_images = {}

    ids.each_with_index do |id, index|
      marker_images[id] = urls[index]
    end
    # current_user = User.find_by_id(session[:current_user_id])
    # activities that the user choosed

    @markers = @day[:day].activities.map do |activity|
      {
        lol: 2,
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: marker_images[activity.day_id]

      }
    end

    # binding.pry
        @city = @trip.city

    if @result[0] && @result[0][:day]
      @date = @result[0][:day][:date]
    else
      @date
    end
    if params[:show].present?
      set_activities
      render 'show'
    else
      render 'your_trip'
    end
  end

  private

  def calculate_day_plan

    activities = @trip.activities.where.not(day_id: nil)

    ids = activities.map { |act| act.day_id }.uniq

    urls = ['https://res.cloudinary.com/dozqozwjs/image/upload/v1628747759/love_1_azo6v7.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747763/love_2_lmpovo.png', 'https://res.cloudinary.com/dozqozwjs/image/upload/v1628747766/love_3_tfswx3.png']

    marker_images = {}

    ids.each_with_index do |id, index|
      marker_images[id] = urls[index]
    end
    # current_user = User.find_by_id(session[:current_user_id])
    # activities that the user choosed

    @markers = activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: marker_images[activity.day_id]

      }
    end
    # Date the user choose
    # start_date = session[:start_date]
    # end_date = session[:end_date]
    @day_activities = []
    cloned = @trip.activities.geocoded.dup.to_a
    days = (@trip.start_date..@trip.end_date).to_a
    sorted_activities = [cloned[0]]
    @city = @trip.city

    days = days.map do |date|
      Day.find_or_create_by(trip: @trip, date: date)
    end

    while cloned.length.positive?
      first_activity = cloned[0]
      rest_activities = cloned[1..-1]
      cloned.delete_at(0)

      unless cloned.empty?
        with_distance = rest_activities.map do |act|
          {
            activity: act,
            distance: first_activity.distance_to(act.to_coordinates)
          }
        end
        cloned = with_distance.sort { |a, b| a[:distance] <=> b[:distance] }.map { |t| t[:activity] }
      end

      sorted_activities << cloned[0] if cloned[0]
    end

app/views/trips/_day_edit_modal.html.erb
<i type="button" class="fas fa-plus" data-toggle="modal" data-target="#moal-<%= day.id %>">
</i>

<!-- Modal -->
<div class="modal fade" id="moal-<%= day.id %>" tabindex="-1" role="dialog" aria-labelledby="moal-<%= day.id %>Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title font-weight-bold" id="moal-<%= day.id %>Label">Add activity</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% activities.where(day: nil).uniq { |a| a.name }.each do |activity| %>
          <div class="title d-flex justify-content-between">
            <div class="">
              <h4><%= activity.name %></h4>
            </div>
            <div>
              <%= link_to assign_day_activity_path(activity, day_id: day.id), method: :patch do %>
                <i class="fas fa-plus"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/_info_window.html.erb
<div class="">
  <div class="title">
    <p><%= activity.name.downcase.capitalize %><p>
  </div>
  <div>
    <p>Address: <%= activity.address %></p>
  </div>
</div>

app/views/trips/index.html.erb
<div class="text-center">
  <h1>Trip history</h1>
  <% if @trips.empty? %>
    <p class="mt-3">Uh-oh! There are no trips yet!</p>
  <% end %>
</div>
<div>

  <div class="row justify-content-center">
    <% @trips.each do |trip| %>
        <div class="col-lg-3 col-md-6 col-xs-12 d-flex align-items-center flex-column card m-3">
          <h2><%= trip.city %></h2>
          <div class="card-content">
            <%= link_to trip_path(trip) do %>
              <%= image_tag "https://source.unsplash.com/400x300/?#{trip.city}" %>
            <% end %>
            <div class="info-card d-flex justify-content-between align-items-center">
              <p><%= trip.start_date %> - <%= trip.end_date %></p>
              <i class="fas fa-heart"></i>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/trips/show.html.erb
<div id="your-trip">

  <div class="container my-5">
      <div class="row">




        <div class="col-md-6 col-sm-12 ">
          <div class="activities-card">

          <div class="header">
            <%# if params[:day].to_i == 0%>
              <%#= link_to your_trip_path do  %>
            <%# end %>
            <% if action_name != 'show' %>
              <% if @prev_day %>
                <%= link_to day_trip_path(@prev_day) do  %>
                  <i class="chevron fas fa-chevron-left"></i>
                <% end %>
              <% else %>
                <%= link_to trip_path(@trip) do  %>
                  <i class="chevron fas fa-chevron-left"></i>
                <% end %>

              <% end %>
            <% else %>
              <%= link_to "", "#" %>
            <% end %>
            <h2><%= @trip.city.downcase.capitalize %><br/><%= @day ? @day.date : 'All dates'  %></h2>
            <% if @next_day %>
              <%= link_to day_trip_path(@next_day) do  %>
                <i class="chevron fas fa-chevron-right"></i>
              <% end %>
            <% else %>
              <%= link_to "", "#" %>
            <% end %>
          </div>


          <% if action_name == 'show' %>
            <% @days.each do |day| %>
              <ul>
                <li>
                  <div class="date d-flex">
                    <div>
                      <p class=""><%= day.date.strftime("%A, %b %d") %></p>
                    </div>
                    <div>
                      <%= render 'day_edit_modal', day: day, activities: @trip.activities %>
                    </div>

                  </div>
                  <div>
                  <% day.activities.each do |activity| %>
                  <div class="d-flex">
                    <div>
                      <%= link_to remove_day_activity_path(activity), method: :patch do %>
                      <i class="fas fa-minus"></i>
                      <% end %>
                    </div>
                    <div>
                      <p class="activity ml-2"><%= activity.name %></p>
                    </div>
                  </div>
                  <% end %>
                  </div>
                </li>
              </ul>
            <% end %>
          <% else %>
            <% @days.each do |day| %>
              <% day.activities.each do |activity| %>
                  <div class="card-product rounded-3 my-2">
                  <%= image_tag activity.picture_url %>
                  <div class="card-product-infos">
                    <h2><%= activity.name %></h2>
                    <i class="fas fa-eye eyecon view-activity" data-id="<%= activity.id %>"></i>
                  </div>
                 </div>

              <% end %>
            <% end %>
          <% end %>






      </div>
        <%= link_to "Delete",
          trip_path(@trip),
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: "Are you sure?" } %>
        <%#= link_to "Change Activity", categories_path({city: @trip.city, start_date: @trip.start_date, end_date: @trip.end_date}) %>
  </div>

      <div class="col-md-6 col-sm-12 ">
        <div class="card-map">
         <h2><%= @trip.city.downcase.capitalize %></h2>
           <div id="map"
             style="width: 100%; height: 600px;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
           </div>
        </div>
      </div>

    </div>

  </div>

  </div>
</div>

app/views/trips/your_trip.html.erb
<div id="your-trip">
  <div class="container">
    <div class="mb-4 mx-auto">
      <%= image_tag "cat3.svg", class: "progress-icon progress-c" %>
    </div>
    <div class="row mb-4 align-items-center">
      <div class="col-12">
        <div class="progress_bar">
          <div class="progress">
            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container my-5">
      <div class="row">
        <div class="col-md-6 col-sm-12 ">
          <div class="activities-card">
            <div class="header">
              <% if params[:day] && (params[:day].to_i - 1).zero? %>
                <%= link_to your_trip_path do  %>
                  <i class="chevron fas fa-chevron-left"></i>
                <% end %>
              <% elsif @prev %>
                <%= link_to prev_day_path(day: params[:day].to_i - 1) do  %>
                  <i class="chevron fas fa-chevron-left"></i>
                <% end %>
              <% else %>
                <%= link_to "", "#" %>
              <% end %>
              <h2><%= @city.downcase.capitalize %><br/><%= @next == 1 || !params[:day] ? 'All dates' : @date %></h2>
              <% if @next %>
                <%= link_to next_day_path(day: @next == 1 ? 1 : params[:day].to_i + 1) do  %>
                  <i class="chevron fas fa-chevron-right"></i>
                <% end %>
              <% else %>
                <%= link_to "", "#" %>
              <% end %>
            </div>

            <% if params[:day] %>
              <% @result.each do |t| %>
                <% t[:activities].each do |act| %>
                  <div class="card-product rounded-3 my-2">
                    <%= image_tag act.picture_url %>
                    <div class="card-product-infos">
                      <h2><%= act.name %></h2>
                      <i class="fas fa-eye eyecon view-activity" data-id="<%= act.id %>"></i>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <ul>
                <% @result.each do |t| %>
                 <% next if !t[:day] %>
                  <li>
                    <p class="date"><%= t[:day].date.strftime("%A, %b %d") %></p>
                    <div>
                      <% t[:activities].each do |act| %>
                        <p class="activity"><%= act.name %></p>
                      <% end %>
                    </div>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
          <div class="my-5">
            <% if !user_signed_in? %>
              <%= link_to 'Save', new_user_registration_path, class: 'btn btn-save' %>
            <% end %>
          </div>
        </div>

        <div class="col-md-6 col-sm-12 ">
          <div class="card-map">
            <h2><%= @city.downcase.capitalize %></h2>
            <div id="map"
              style="width: 100%; height: 600px;"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>