config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :trips
  get '/trips/days/:id', to: 'trips#day', as: :day_trip
  get '/your_trip', to: 'trips#your_trip', as: :your_trip
  get '/your_trip/next', to: 'trips#next', as: :next_day
  get '/your_trip/prev', to: 'trips#prev', as: :prev_day
  get '/about', to: 'pages#about', as: :about
  resources :categories
  resources :activities do
    member do
      patch :assign_day
      patch :remove_day
    end
  end

  get '/components', to: 'pages#components', as: :components

end

app/views/shared/_activity_card.html.erb
<div class="individual-activities-card">
  <%= image_tag picture_url %>
  <div class="row card-info overscroll justify-content-center align-items-center">
    <div class="col-9 activity-name">
      <p><%= name %></p>
    </div>
    <div class="col-3 text-left">
      <i class="fas fa-eye eyecon view-activity" data-id="<%= id %>"></i>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-between px-5">
  <div class="footer-left d-flex justify-content-center align-items-center p-2">
    <p>Contacts</p>
    <%= link_to "https://github.com/Ladeconne/Plan-it-for-me", class:"pl-2" do%>
      <i class="footer-icon fab fa-github"></i>
    <% end %>
    <p class="d-inline-block footer-hash pl-2">
      {
      <%= link_to "https://github.com/jessicakalip", id:"jess-github" do%>
        "Jess" => <i class="footer-icon fab fa-github"></i>,
      <% end %>
      <%= link_to "https://github.com/Ladeconne", id:"lade-github" do%>
        "Yves" => <i class="footer-icon fab fa-github"></i>,
      <% end %>
      <%= link_to "https://github.com/Yitangwang123", id:"tang-github" do%>
        "Yitang" => <i class="footer-icon fab fa-github"></i>,
      <% end %>
      <%= link_to "https://github.com/tannerbrice", id:"tann-github" do%>
        "Tanner" => <i class="footer-icon fab fa-github"></i>
      <% end %>
      }
    </p>
  </div>
  <div class="footer-right d-flex align-items-center">
    <p>Created by: Team Plan It For Me @Le Wagon</p>
  </div>
</div>

app/views/shared/_loading.html.erb
<div class="box">
  <div class="cat-box">
    <div class="cat">
      <div class="helf-box helf-box--ass">
        <div class="helf-box clip">
          <div class="cat__body"></div>
        </div>
        <div class="cat__ass">
          <div class="cat__body--fake"></div>
          <div class="cat__foots"></div>
          <div class="cat__tail"></div>
        </div>
      </div>
      <div class="helf-box helf-box--head">
        <div class="cat__head">
          <div class="cat__face">
            <div class="cat__ears"></div>
            <div class="cat__eyes"></div>
            <div class="cat__mouth"></div>
            <div class="cat__mustache"></div>
          </div>
          <div class="cat__foots"></div>
        </div>
        <div class="helf-box clip">
          <div class="cat__body"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex align-items-baseline">
    <%= link_to :root, class: "navbar-brand" do %>
      <div class="d-flex align-items-baseline">
        <%= image_tag "cat.svg" %>
        <h1 class="m-0">PLAN IT FOR ME</h1>
      </div>
    <% end %>
    <%= link_to "About", about_path, class: "nav-link" %>
    <%= link_to "New Trip", :root, class: "nav-link" %>
    <% if user_signed_in?  %>
      <%= link_to "Saved Trips", trips_path, class: "nav-link" %>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "Avatar.png", id: "navbarDropdown", data: {toggle: "dropdown"}, aria: {haspopup: "true"}, aria: {expanded: "false"}, class: "avatar dropdown toggle" %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item dropdown">
            <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item dropdown">
            <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_polaroid_card.html.erb
<div class="card-polaroid">
  <h2><%= name %></h2>
  <%= image_tag "https://source.unsplash.com/400x300/?#{name}" %>
  <%= yield %>
</div>