config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :trips
  get '/trips/days/:id', to: 'trips#day', as: :day_trip
  get '/your_trip', to: 'trips#your_trip', as: :your_trip
  get '/your_trip/next', to: 'trips#next', as: :next_day
  get '/your_trip/prev', to: 'trips#prev', as: :prev_day
  get '/about', to: 'pages#about', as: :about
  resources :categories
  resources :activities do
    member do
      patch :assign_day
      patch :remove_day
    end
  end

  get '/components', to: 'pages#components', as: :components

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :tags
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    session[:current_trip] = nil

    # if params[:trip_id].present?
    #    # session[:current_trip]
    # end

    unless valid?
      render 'pages/home'
      return
    end
    session[:city] = params.dig(:search, :city).split(",").first
    session[:start_date] = params.dig(:search, :start_date)
    session[:end_date] = params.dig(:search, :end_date)
  end

  private

  def valid?
    @today = Date.today
    params[:search][:start_date] = params.dig(:search, :start_date).to_date
    params[:search][:end_date] = params[:search][:start_date] + params.dig(:search, :start_duration).to_i.days
    unless params.dig(:search, :city).present?
      @errors = { city: 'Please add a valid location' }
      return false
    end
    unless params.dig(:search, :start_date).present?
      @errors = { start_date: 'Please add a start date' }
      return false
    end
    unless params.dig(:search, :start_date).to_date >= @today
      @errors = { start_date: 'Cant choose a date in the past' }
      return false
    end
    unless params.dig(:search, :end_date).present?
      @errors = { end_date: 'Please add an end date' }
      return false
    end
    unless params.dig(:search, :start_date) <= params.dig(:search, :end_date)
      @errors = { end_date: 'Cant choose a date before the start date' }
      return false
    end

    # Finish with validating start and end date.

    true
  end
end

app/views/categories/index.html.erb
<%= render 'shared/loading' %>

<div id="interests">
  <div class="container mb-5">
    <div class="row mb-1 mx-auto align-items-center">
      <div class="col-3">
      </div>
      <div class="col-6">
        <%= image_tag "cat1.svg", class: "progress-icon progress-a" %>
      </div>
      <div class="col-3">
        <p class="prompt next invisible">Next</p>
      </div>
    </div>

    <div class="row mb-4 align-items-center">
      <div class="col-1" style="height: 72px">
      </div>
      <div class="col-10">
        <div class="progress_bar">
          <div class="progress">
            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 33%" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
      <div class="col-1 right-arrow" style="height: 72px">
      </div>
    </div>
    <h1>SELECT YOUR INTERESTS:</h1>
    <div class="instructions">
      <p>Select at least <em>4</em> categories to continue</p>
    </div>

    <%= simple_form_for :search, url: activities_path, method: 'get', html: { id: 'category-form' } do |f| %>
      <div class="row justify-content-center">

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="nature" value="nature">
            <label data-target="nature">
              <div class="card-polaroid">
                <h2>Nature</h2>
                <%= image_tag "nature.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="religion" value="religion">
            <label data-target="religion">
              <div class="card-polaroid">
                <h2>Religion</h2>
                <%= image_tag "religion.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="museum" value="museum">
            <label data-target="museum">
              <div class="card-polaroid">
                <h2>Museum</h2>
                <%= image_tag "museum.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="art" value="art">
            <label data-target="art">
              <div class="card-polaroid">
                <h2>Art</h2>
                <%= image_tag "art.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="music" value="music">
            <label data-target="music">
              <div class="card-polaroid">
                <h2>Music</h2>
                <%= image_tag "music.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="history" value="history">
            <label data-target="history">
              <div class="card-polaroid">
                <h2>History</h2>
                <%= image_tag "history.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="sport" value="sport">
            <label data-target="sport">
              <div class="card-polaroid">
                <h2>Sport</h2>
                <%= image_tag "sport.jpg" %>
              </div>
            </label>
          </div>

          <div class="col-lg-3 col-md-6 interest-col">
            <input class="image-checkbox" hidden type="checkbox" name="search[categories][]" id="shopping" value="shopping">
            <label data-target="shopping">
              <div class="card-polaroid">
                <h2>Shopping</h2>
                <%= image_tag "shopping.jpg" %>
              </div>
            </label>
          </div>
      </div>
      <h1>OR:</h1>
      <div id="select-all-categories" type="button" class="btn btn-flat big-button"><p><span>Select</span> All Categories</p></div>
    <% end %>
  </div>
</div>